services:
  api:
    build:
      context: ./apps/api
    env_file: ./apps/api/.env
    ports:
      - "3001:3001"

  web:
    build:
      context: ./apps/web
    ports:
      - "5173:5173"
    depends_on:
      - api
