services:
  db:
    image: postgres:16-alpine
    container_name: helix-pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: helix
      POSTGRES_PASSWORD: helix
      POSTGRES_DB: helix
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U helix -d helix"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: helix-api
    restart: unless-stopped
    env_file:
      - apps/api/.env          # put secrets here
    environment:
      NODE_ENV: production
      # Override DB host for container networking (service name "db")
      DATABASE_URL: postgresql://helix:helix@db:5432/helix?schema=public
    depends_on:
      db:
        condition: service_healthy
    ports: ["3001:3001"]

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: helix-web
    restart: unless-stopped
    depends_on:
      api:
        condition: service_started
    ports: ["5173:80"]

volumes:
  pgdata:
