name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Web install & build
        run: |
          cd apps/web
          npm ci || npm install
          npm run build

      - name: API lint (requirements install)
        run: |
          cd apps/api
          python -m venv .venv
          . .venv/bin/activate || source .venv/bin/activate || true
          pip install -r requirements.txt
          python -c "import fastapi,uvicorn"

      - name: Archive frontend dist
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: apps/web/dist
